
@server=http://localhost:4004
### list all the students
GET {{server}}/odata/v4/mysrvdemo/GetStudent

### list student with email demo
GET {{server}}/odata/v4/mysrvdemo/GetStudent(email='demo@demo.com')

### list student with email john
GET {{server}}/odata/v4/mysrvdemo/GetStudent(email='john@demo.com')

### list student with nonexisting email
GET {{server}}/odata/v4/mysrvdemo/GetStudent(email='ben@demo.com')

### list student with email john and first name
### it needs first_name as key in cds
GET {{server}}/odata/v4/mysrvdemo/GetStudent(email='john@demo.com',first_name='john')


### list student with email john and first name
### it needs first_name as key in cds
GET {{server}}/odata/v4/mysrvdemo/GetStudent(email='ajay@demo.com',first_name='ajay')

### list student with email john and first name ajay, not found
### it needs first_name as key in cds
GET {{server}}/odata/v4/mysrvdemo/GetStudent(email='john@demo.com',first_name='john')

### list student with john as first name
### it needs first_name as key in cds
GET {{server}}/odata/v4/mysrvdemo/GetStudent(first_name='john')

### list student with email john and first name ajay, not found
### it needs first_name as key in cds
GET {{server}}/odata/v4/mysrvdemo/GetStudent(email='john@demo.com')

### POST
POST {{server}}/odata/v4/mysrvdemo/UpdateStudent HTTP/1.1
Content-Type: application/json

{
    "first_name":"antika",
    "email": "demo@demo.com"
}

### POST
POST {{server}}/odata/v4/mysrvdemo/UpdateStudent HTTP/1.1
Content-Type: application/json

{
    "first_name":"antika",
    "email": "demo1@demo.com"
}


### POST
POST {{server}}/odata/v4/mysrvdemo/UpdateStudentJohn HTTP/1.1
Content-Type: application/json

{
    "first_name":"john"
}

### InsertStudent
POST {{server}}/odata/v4/mysrvdemo/InsertStudent HTTP/1.1
Content-Type: application/json

{
    "email": "antika@demo.com",
    "first_name":"antika",
    "last_name": "lastname",
    "date_sign_up":"2024-08-02"
}

### DELETE
POST {{server}}/odata/v4/mysrvdemo/DeleteStudent HTTP/1.1
Content-Type: application/json

{
    "email":"antika@demo.com"
}

